use_frameworks!

source 'https://github.com/RichieZhl/Spec.git'
source 'http://git.dev.qianmi.com/adminapp/qmspec-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'react-native-gesture-handler_Example' do
  pod 'react-native-gesture-handler', :path => '../'

  target 'react-native-gesture-handler_Tests' do
    inherit! :search_paths

    
  end
end
